language: generic
sudo: false

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1401"
    MACRO_COUNT=77
    FLYWAY_BUILD="4.2.0"
  matrix:
    - USE_MAP=aurora
    - USE_MAP=runtime
    - USE_MAP=exodus

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
    - $HOME/flyway-${FLYWAY_BUILD}

addons:
  mariadb: '10.1'
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - mysql -e 'CREATE DATABASE ss13_test;'
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
  - chmod +x ./install-flyway.sh
  - ./install-flyway.sh

script:
  - export LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH
  - $HOME/flyway-${FLYWAY_BUILD}/flyway migrate -user=root -password= -url=jdbc:mysql://localhost:3306/ss13_test
  - shopt -s globstar
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
  - (! grep -E "<\s*span\s+class\s*=\s*('[^'>]+|[^'>]+')\s*>" **/*.dm)
  - (num=`grep -E '\\\\(red|blue|green|black|b|i[^mc])' **/*.dm | wc -l`; echo "$num escapes (expecting ${MACRO_COUNT} or less)"; [ $num -le ${MACRO_COUNT} ])
  - awk -f tools/indentation.awk **/*.dm
  - md5sum -c - <<< "94c0d540b3b0f008fbc4353e667de690 *html/changelogs/example.yml"
  - python tools/TagMatcher/tag-matcher.py ../..
  - python tools/GenerateChangelog/ss13_genchangelog.py html/changelog.html html/changelogs --dry-run
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - cp config/example/* config/
  - scripts/dm.sh -DUNIT_TEST -M$USE_MAP aurorastation.dme
  - grep "0 warnings" build_log.txt
  - DreamDaemon aurorastation.dmb -invisible -trusted -core 2>&1 | tee log.txt
  - grep "All Unit Tests Passed" log.txt
  - (! grep "runtime error:" log.txt)
