language: generic
sudo: false

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1488"
    MACRO_COUNT=77
    FLYWAY_BUILD="5.2.4"
    NODE_VERSION=10
    RUST_G_VERSION="0.4.1"
    SPACEMAN_DMM_VERSION="suite-1.1"
  matrix:
    - USE_MAP=aurora
    - USE_MAP=runtime
    - USE_MAP=exodus

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
    - $HOME/flyway-${FLYWAY_BUILD}
    - vueui/dist
    - $HOME/rust_g-${RUST_G_VERSION}

addons:
  mariadb: '10.3'
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - libssl-dev:i386
      - pkg-config:i386
      - gcc-multilib
      - "python3"
      - "python3-pip"

node_js:
  - "10"

install:
  - mysql -e 'CREATE DATABASE ss13_test;'
  - chmod +x ./scripts/install-byond.sh
  - ./scripts/install-byond.sh
  - chmod +x ./scripts/install-flyway.sh
  - ./scripts/install-flyway.sh
  - export LD_LIBRARY_PATH=./:$HOME/rust_g-$RUST_G_VERSION:$LD_LIBRARY_PATH
  - shopt -s globstar
  - chmod +x ./scripts/rust_g.sh
  - ./scripts/rust_g.sh

stages:
  - code check
  - test


script:
  - $HOME/flyway-${FLYWAY_BUILD}/flyway migrate -user=root -password= -url=jdbc:mariadb://localhost:3306/ss13_test
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - cp config/example/* config/
  - scripts/dm.sh -DUNIT_TEST -M$USE_MAP aurorastation.dme
  - grep "0 warnings" build_log.txt
  - DreamDaemon aurorastation.dmb -invisible -trusted -core 2>&1 | tee log.txt
  - grep "All Unit Tests Passed" log.txt
  - (! grep "runtime error:" log.txt)

jobs:
  include:
    - stage: code check
      install:
        - pip install --user PyYaml -q
        - pip install --user beautifulsoup4 -q
        - pip3 install --user bidict -q
        - chmod +x ./vueui/install
        - ./vueui/install
        - chmod +x ./scripts/install-spaceman-dmm.sh
        - ./scripts/install-spaceman-dmm.sh dreamchecker
        - chmod +x ./scripts/rust_g.sh
        - ./scripts/rust_g.sh
      script:
        - (! grep 'step_[xy]' maps/**/*.dmm)
        - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
        - (! grep -E "<\s*span\s+class\s*=\s*('[^'>]+|[^'>]+')\s*>" **/*.dm)
        - (! grep -r --include=\*.dm '#define UIDEBUG' ./)
        - (! grep -r --include=\*.dm 'to_chat(.*,\s*link(' ./)
        - (cd vueui && (npm run lint | tee lint.log))
        - grep "No lint errors found!" vueui/lint.log
        - (cd vueui && npm run build)
        - (num=`grep -E '\\\\(red|blue|green|black|b|i[^mc])' **/*.dm | wc -l`; echo "$num escapes (expecting ${MACRO_COUNT} or less)"; [ $num -le ${MACRO_COUNT} ])
        - awk -f tools/indentation.awk **/*.dm
        - md5sum -c - <<< "60a49502d9f6dfdcc255deb98c901b72 *html/changelogs/example.yml"
        - python tools/TagMatcher/tag-matcher.py ../..
        - python tools/GenerateChangelog/ss13_genchangelog.py html/changelog.html html/changelogs --dry-run
        - python3 tools/mapmerge2/travis_mapcheck.py
        - ~/dreamchecker
