environment = "aurorastation.dme"

[langserver]
dreamchecker = true

[debugger]
engine = "auxtools"

[code_standards]
disallow_relative_type_definitions = true
disallow_relative_proc_definitions = true

[dmdoc]
use_typepath_names = true

[diagnostics]
sets_directive_twice = "error"
invalid_lint_directive_value = "error"
invalid_set_value = "error"
ambiguous_in_lhs = "error"
ambiguous_not_bitwise = "error"
no_typehint_implicit_new = "error"
field_access_static_type = "error"
proc_call_static_type = "error"
proc_has_no_parent = "error"
no_operator_overload = "error"
unreachable_code = "error"
control_condition_static = "error"
if_condition_determinate = "error"
loop_condition_determinate = "error"
integer_precision_loss = "error"
static_in_proc_parameter = "error"
semicolon_in_proc_parameter = "error"
in_precedes_as = "error"
tmp_no_effect = "error"
final_no_effect = "error"
as_local_var = "error"
duplicate_include = "error"
macro_redefined = "error"
macro_undefined_no_definition = "error"
override_precedes_definition = "error"

[display]
error_level = "hint"
